### ISSUE TITLE
server not able to handel the request

### ISSUE THREAD

**Issue by supermario18b** [Dopingus/cert-manager-webhook-dynu#25]
Hi,
thank for the webhook, I noticed that when I try to get new certificates, I get this error:

`Error presenting challenge: the server is currently unable to handle the request (post dynu.com.github.dopingus.cert-manager-webhook-dynu)`

I'm sure that last week it worked. The fields "groupName" and "solverName" in the "ClusterIssuer" are set like this:

`groupName: com.github.dopingus.cert-manager-webhook-dynu`
`solverName: dynu`

Should I have to change something or is it a temporary error?

Thanks in Advance,

supermario18b

**Comment by rbaumgar** [comment]
I could create some certificates today without any issues. 
How is your solver within (cluster)issuer configured?

**Comment by supermario18b** [comment]
Hi, 
thank you for the reply. Here is my clusterissuer manifest:

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dynu-mydomain
spec:
  acme:
    
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: myemail@not-example.com 
    privateKeySecretRef:
      name: letsencrypt-secret
    solvers:
      - dns01:
          cnameStrategy: Follow
          webhook:
            groupName: com.github.dopingus.cert-manager-webhook-dynu
            solverName: dynu
            config:
              secretName: dynu-secret # Adjust this in case you changed the secretName.
              
Sorry for the formatting, I didn't get it better.

**Comment by supermario18b** [comment]
The "READY" status of the clusterissuer is shown as "True".

**Comment by rbaumgar** [comment]
I have some more settings, eg ApiUrl:

```
spec:
  acme:
    email: <my-mail@domain>
    preferredChain: ''
    privateKeySecretRef:
      name: letsencrypt-clusterissuer
    server: 'https://acme-v02.api.letsencrypt.org/directory'
    solvers:
      - dns01:
          cnameStrategy: Follow
          webhook:
            config:
              apiUrl: 'https://api.dynu.com/v2'
              secretName: dynu-secret
              zoneName: <my-dynu.domain>
            groupName: com.github.dopingus.cert-manager-webhook-dynu
            solverName: dynu
```
